# Generated by Django 4.1 on 2024-09-27 08:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="create_date",
            field=models.DateTimeField(
                default=datetime.datetime.now, verbose_name="创建日期"
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="job_name",
            field=models.CharField(max_length=250, verbose_name="职位名称"),
        ),
    ]
