# Generated by Django 4.1 on 2024-10-10 06:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("interview", "0002_remove_candidate_second_recommend_position"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="candidate",
            name="first_recommend_position",
        ),
    ]
